### ISSUE TITLE
Setup a basic client/server project!

### ISSUE THREAD

**Issue by dylanwatsonsoftware** [lotsabackscatter/agileboard#1]
So my thought is:

Server
- node.js/express

Client
- angular 2
  - Via angular-cli?

**Comment by dylanwatsonsoftware** [comment]
I've pushed 3 branches with alternative angular2/express starter projects:

- https://github.com/lotsabackscatter/agileboard/tree/angular2-full-stack
- https://github.com/lotsabackscatter/agileboard/tree/ng-fullstack
- https://github.com/lotsabackscatter/agileboard/tree/angular2-webpack-starter

I haven't had a play with them yet but they are the options... unless there is a better one?

What do you think @kahgoh, @StevenGBrown, @kirk93, @kobanator, @DjOli, @bwobbones?

**Comment by kobanator** [comment]
https://github.com/angular/angular-cli might have been the one steve was talking about?

**Comment by dylanwatsonsoftware** [comment]
angular-cli is good and in fact one of the branches is generated (partly) with it but it doesn't provide a backend. So we either need to wire up our own or use one that someone has already put together 😀

**Comment by StevenGBrown** [comment]
Option 1 looks good. The angular cli front-end and node back-end one. Finally, a way to keep track of all the cats in my brother's share house. :heart_eyes_cat:

I had to make a small change to get it working: 5b76711.

Happy with this one @lotsabackscatter? Shall we get this thing started? :tada:

**Comment by dylanwatsonsoftware** [comment]
Sure. Why not? Let's do it

**Comment by dylanwatsonsoftware** [comment]
Who wants to submit the first PR to merge it in then?
